# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GraphViz-DBI-General
version:      0.1
version_from: lib/GraphViz/DBI/General.pm
installdirs:  site
requires:
    DBI:                           0
    GraphViz:                      0
    GraphViz::DBI:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
